# Generated by Django 5.2 on 2025-04-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='firmware/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_latest', models.BooleanField(default=False)),
            ],
        ),
    ]
