# Generated by Django 5.2 on 2025-04-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='air_quality',
            field=models.FloatField(default=0.0),
        ),
    ]
