# Generated by Django 5.2 on 2025-04-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_firmwareupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirmwareUpload',
        ),
    ]
